/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/users/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["signUp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/reissue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["reissue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/todos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPetTodos"];
    put?: never;
    post: operations["createTodo"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/pets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getUserPets"];
    put?: never;
    post: operations["registerPet"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/medical/medications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["recordMedication"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/medical/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["recordMedicalLog"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/files/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["uploadFile"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/expenses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["recordExpense"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/diaries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPetDiaries"];
    put?: never;
    post: operations["createDiaryEntry"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/todos/{todoId}/toggle": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["toggleTodo"];
    trace?: never;
  };
  "/api/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAllUsers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getUserProfile"];
    put?: never;
    post?: never;
    delete: operations["deleteUser"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/pets/{petId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPetDetail"];
    put?: never;
    post?: never;
    delete: operations["deletePet"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["healthCheck"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/todos/{todoId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteTodo"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/medical/medications/{medicationId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteMedication"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/medical/logs/{logId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteMedicalLog"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/expenses/{expenseId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteExpense"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/diaries/{diaryId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteDiaryEntry"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UserRequestDto: {
      email?: string;
      password?: string;
      nickname?: string;
    };
    LoginResponseDto: {
      accessToken?: string;
      refreshToken?: string;
      tokenType?: string;
      /** Format: int64 */
      userId?: number;
      email?: string;
    };
    LoginRequestDto: {
      email?: string;
      password?: string;
    };
    LocalTime: {
      /** Format: int32 */
      hour?: number;
      /** Format: int32 */
      minute?: number;
      /** Format: int32 */
      second?: number;
      /** Format: int32 */
      nano?: number;
    };
    TodoRequestDto: {
      title?: string;
      /** @enum {string} */
      frequency?: "NONE" | "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
      targetTime?: components["schemas"]["LocalTime"];
      /** Format: date */
      dueDate?: string;
      alarmTypes?: (
        | "TEN_MIN_BEFORE"
        | "THIRTY_MIN_BEFORE"
        | "ONE_HOUR_BEFORE"
        | "ONE_DAY_BEFORE"
        | "ONE_WEEK_BEFORE"
      )[];
      /** Format: int64 */
      medicationId?: number;
      /** Format: int64 */
      medicalLogId?: number;
    };
    PetRequestDto: {
      name?: string;
      breed?: string;
      /** Format: date */
      birthDate?: string;
      isNeutered?: boolean;
      currentWeight?: number;
      profileImageUrl?: string;
      petType?: string;
      petTheme?: string;
      gender?: string;
      coatColor?: string;
      allergies?: string;
      /** Format: date */
      adoptionDate?: string;
      microchipNumber?: string;
      notes?: string;
    };
    MedicationRequestDto: {
      name?: string;
      /** Format: date */
      startDate?: string;
      /** Format: date */
      endDate?: string;
      /** Format: int32 */
      expenseAmount?: number;
    };
    MedicalLogRequestDto: {
      /** Format: date */
      visitDate?: string;
      purpose?: string;
      diagnosis?: string;
      vetNotes?: string;
      /** Format: date */
      nextVisitDate?: string;
      weightAtVisit?: number;
      /** Format: int32 */
      expenseAmount?: number;
    };
    ExpenseRequestDto: {
      category?: string;
      /** Format: int32 */
      amount?: number;
      /** Format: date */
      expenseDate?: string;
      memo?: string;
      /** Format: int64 */
      medicalLogId?: number;
      /** Format: int64 */
      medicationId?: number;
    };
    DiaryEntryRequestDto: {
      photoUrl?: string;
      content?: string;
      /** Format: date */
      diaryDate?: string;
    };
    UserResponseDto: {
      /** Format: int64 */
      id?: number;
      email?: string;
      nickname?: string;
    };
    TodoResponseDto: {
      /** Format: int64 */
      id?: number;
      title?: string;
      /** @enum {string} */
      frequency?: "NONE" | "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
      targetTime?: components["schemas"]["LocalTime"];
      /** Format: date */
      dueDate?: string;
      isCompleted?: boolean;
      /** Format: date-time */
      completedAt?: string;
      enabledAlarms?: (
        | "TEN_MIN_BEFORE"
        | "THIRTY_MIN_BEFORE"
        | "ONE_HOUR_BEFORE"
        | "ONE_DAY_BEFORE"
        | "ONE_WEEK_BEFORE"
      )[];
    };
    PetResponseDto: {
      /** Format: int64 */
      id?: number;
      name?: string;
      breed?: string;
      /** Format: date */
      birthDate?: string;
      isNeutered?: boolean;
      profileImageUrl?: string;
      latestWeight?: number;
      petType?: string;
      petTheme?: string;
      gender?: string;
      coatColor?: string;
      allergies?: string;
      /** Format: date */
      adoptionDate?: string;
      microchipNumber?: string;
      notes?: string;
    };
    DiaryEntryResponseDto: {
      /** Format: int64 */
      id?: number;
      photoUrl?: string;
      content?: string;
      /** Format: date */
      diaryDate?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  signUp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": number;
        };
      };
    };
  };
  reissue: {
    parameters: {
      query: {
        refreshToken: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["LoginResponseDto"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query: {
        userId: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["LoginResponseDto"];
        };
      };
    };
  };
  getPetTodos: {
    parameters: {
      query: {
        petId: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["TodoResponseDto"][];
        };
      };
    };
  };
  createTodo: {
    parameters: {
      query: {
        petId: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TodoRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": number;
        };
      };
    };
  };
  getUserPets: {
    parameters: {
      query: {
        userId: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PetResponseDto"][];
        };
      };
    };
  };
  registerPet: {
    parameters: {
      query: {
        userId: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PetRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": number;
        };
      };
    };
  };
  recordMedication: {
    parameters: {
      query: {
        petId: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MedicationRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": number;
        };
      };
    };
  };
  recordMedicalLog: {
    parameters: {
      query: {
        petId: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MedicalLogRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": number;
        };
      };
    };
  };
  uploadFile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": {
            [key: string]: string;
          };
        };
      };
    };
  };
  recordExpense: {
    parameters: {
      query: {
        petId: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExpenseRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": number;
        };
      };
    };
  };
  getPetDiaries: {
    parameters: {
      query: {
        petId: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["DiaryEntryResponseDto"][];
        };
      };
    };
  };
  createDiaryEntry: {
    parameters: {
      query: {
        petId: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DiaryEntryRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": number;
        };
      };
    };
  };
  toggleTodo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        todoId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAllUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserResponseDto"][];
        };
      };
    };
  };
  getUserProfile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserResponseDto"];
        };
      };
    };
  };
  deleteUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getPetDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        petId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PetResponseDto"];
        };
      };
    };
  };
  deletePet: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        petId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  healthCheck: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": {
            [key: string]: string;
          };
        };
      };
    };
  };
  deleteTodo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        todoId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteMedication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        medicationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteMedicalLog: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        logId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteExpense: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        expenseId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteDiaryEntry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        diaryId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
